export const NEW_CHARACTER = 'NEW_CHARACTER';
export const CHANGE_CHARACTER = 'CHANGE_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';

export const NEW_CHARACTER_BURDEN = 'NEW_CHARACTER_BURDEN';
export const CHANGE_CHARACTER_BURDEN = 'CHANGE_CHARACTER_BURDEN';
export const REMOVE_CHARACTER_BURDEN = 'REMOVE_CHARACTER_BURDEN';

export const NEW_CHARACTER_POWER = 'NEW_CHARACTER_POWER';
export const CHANGE_CHARACTER_POWER = 'CHANGE_CHARACTER_POWER';
export const REMOVE_CHARACTER_POWER = 'REMOVE_CHARACTER_POWER';

export const NEW_CHARACTER_STUNT = 'NEW_CHARACTER_STUNT';
export const CHANGE_CHARACTER_STUNT = 'CHANGE_CHARACTER_STUNT';
export const REMOVE_CHARACTER_STUNT = 'REMOVE_CHARACTER_STUNT';

export const NEW_CHARACTER_EQUIPMENT = 'NEW_CHARACTER_EQUIPMENT';
export const CHANGE_CHARACTER_EQUIPMENT = 'CHANGE_CHARACTER_EQUIPMENT';
export const REMOVE_CHARACTER_EQUIPMENT = 'REMOVE_CHARACTER_EQUIPMENT';
